Add Features to Boston Dataset
Send Feedback
For the Boston dataset, your task is to add all 2 degree features to the dataset and compare scores for the original dataset and new dataset with added features.

In [58]:
import numpy as np

from sklearn import datasets

boston = datasets.load_boston()

In [59]:
X = boston.data
Y = boston.target

In [60]:
import pandas as pd

df= pd.DataFrame(X)
df.columns = boston.feature_names

In [36]:
#now here we need to add all the features
#lets start with one : 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX','PTRATIO', 'B', 'LSTAT'
#df['CRIM_CRIM'] = df['CRIM'] ** 2
#df['CRIM_ZN'] = df['CRIM'] * df['ZN']

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,CRIM_CRIM,CRIM_ZN
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,0.000040,0.11376
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,0.000746,0.00000
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,0.000745,0.00000
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,0.001048,0.00000
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,0.004768,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,0.003923,0.00000
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,0.002049,0.00000
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,0.003692,0.00000
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,0.012010,0.00000
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,0.002248,0.00000

In [61]:
cols = boston.feature_names
len(cols)

for i in range(len(cols)):
    k = cols[i] + '_' + cols[i]
    df[k] = df[cols[i]] ** 2
    for j in range(i+1,len(cols)):
        w = cols[i] + '_' + cols[j]
        df[w] = df[cols[i]] * df[cols[j]]

In [62]:
X2 = df.values

array([[6.32000000e-03, 1.80000000e+01, 2.31000000e+00, ...,
        1.57529610e+05, 1.97656200e+03, 2.48004000e+01],
       [2.73100000e-02, 0.00000000e+00, 7.07000000e+00, ...,
        1.57529610e+05, 3.62766600e+03, 8.35396000e+01],
       [2.72900000e-02, 0.00000000e+00, 7.07000000e+00, ...,
        1.54315409e+05, 1.58310490e+03, 1.62409000e+01],
       ...,
       [6.07600000e-02, 0.00000000e+00, 1.19300000e+01, ...,
        1.57529610e+05, 2.23851600e+03, 3.18096000e+01],
       [1.09590000e-01, 0.00000000e+00, 1.19300000e+01, ...,
        1.54802902e+05, 2.54955600e+03, 4.19904000e+01],
       [4.74100000e-02, 0.00000000e+00, 1.19300000e+01, ...,
        1.57529610e+05, 3.12757200e+03, 6.20944000e+01]])

In [63]:
from sklearn import model_selection
X1_train,X1_test,Y1_train,Y1_test = model_selection.train_test_split(X,Y,random_state = 0)
X2_train,X2_test,Y2_train,Y2_test = model_selection.train_test_split(X2,Y,random_state = 0)

In [64]:
from sklearn.linear_model import LinearRegression

alg1 = LinearRegression()
alg1.fit(X1_train,Y1_train)
alg2 = LinearRegression()
alg2.fit(X2_train,Y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [65]:
score1_train = alg1.score(X1_train,Y1_train)
score1_test = alg1.score(X1_test,Y1_test)
print('score1_train',score1_train)
print('score1_test',score1_test)


score2_train = alg2.score(X2_train,Y2_train)
score2_test = alg2.score(X2_test,Y2_test)
print('score2_train',score2_train)
print('score2_test',score2_test)

score1_train 0.7697699488741149
score1_test 0.6354638433202129
score2_train 0.9520519609032729
score2_test 0.6074721959695066